logging.level.root: INFO
server.port: 8099

spring.datasource:
  url: jdbc:mysql://localhost:3306/superhero?createDatabaseIfNotExist=true&useSSL=false&rewriteBatchedStatements=true
  username: admin
  password: admin
  driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1

spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: false

security:
  signing-key: fiXty1x4WHtVZha
  security-realm: Payworks Realm
  jwt:
     client-id: payworks
     client-secret: payworks-secret
     grant-type-password: password
     grant-type-refresh-token: refresh_token
     scope-read: read
     scope-write: write
     resource-ids: payworksresourceid