logging.level.root: INFO
server.port: 8080

spring.datasource:
  #url: jdbc:mysql://localhost:3306/superhero?createDatabaseIfNotExist=true&useSSL=false&rewriteBatchedStatements=true
  #username: admin
  #password: admin
  url: jdbc:mysql://payworks-rds-mysql.c8kdjalqnuyw.us-west-2.rds.amazonaws.com:3306/superhero?createDatabaseIfNotExist=true&useSSL=false&rewriteBatchedStatements=true
  username: payworks
  password: payworks
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: false

security:
  signing-key: fiXty1x4WHtVZha
  security-realm: Payworks Realm
  jwt:
     client-id: payworks
     client-secret: payworks-secret
     grant-type-password: password
     grant-type-refresh-token: refresh_token
     scope-read: read
     scope-write: write
     resource-ids: payworksresourceid